FROM rocker/rstudio:4.4.2
USER root

RUN install2.r --error --skipinstalled --deps TRUE \
  dplyr tidyr ggplot2 cowplot tibble forcats lubridate \
  stringr readr purrr readxl usethis devtools \
  && rm -rf /tmp/downloaded_packages

WORKDIR /home/rstudio/amazonasdatahub

EXPOSE 8787
